# Generated by Django 3.2.8 on 2021-11-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacen',
            name='codigo',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='codigo',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='codigo',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
