# Generated by Django 3.2.8 on 2021-11-09 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211108_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('GERENTE', 'GERENTE'), ('ADMINISTRACION', 'ADMINISTRACION')], default='GERENTE', max_length=30),
        ),
    ]
